### ISSUE TITLE
Stored XSS in "exclusive" field - SensitiveWords

### ISSUE THREAD

**Issue by Peithon** [eddy8/LightCMS#18]
### Description -

There's no escape being done before printing out the value of `noun`、`verb`、`exclusive` in the SensitiveWords page.

### Steps to reproduce -

- Navigate to http://lightcms.bituier.com/admin/login &  Log in to the background with the account admin and password admin

- Navigate to http://lightcms.bituier.com/admin/SensitiveWords/create & add the below-shared payload as the `exclusive` field value.
Payload - `</span><img src=1 onerror=alert(1) /><span>`

- Visit page http://lightcms.bituier.com/admin/SensitiveWords, the payload will be triggered.

![image](https://user-images.githubusercontent.com/37824204/105807257-9d38f200-5fe0-11eb-879a-8cf1264f851e.png)
![image](https://user-images.githubusercontent.com/37824204/105807423-ed17b900-5fe0-11eb-83b3-a8379c479b7c.png)

**Comment by eddy8** [comment]
Fixed. Thanks for your feedback.
