### ISSUE TITLE
请问如果要集成OSS 需要调整那些东西呢

### ISSUE THREAD

**Issue by edisonX** [eddy8/lightCMS#29]
企业图片加载速度比较忙，希望把图片上传集成到oss

NEditorController 里面是有存储图片的入口，
是否只需要uploadImage

`$result = $file->store(date('Ym'), config('light.neditor.disk'));
        if (!$result) {
            return [
                'code' => 3,
                'msg' => '上传失败'
            ];
        }`

改写入口，还是可以通过扩展包来增加新的呢

**Comment by eddy8** [comment]
参考：https://github.com/eddy8/LightCMS#%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0
