### ISSUE TITLE
Host header attack vulnerability exists in Lightcms 2.0 . An attacker can use man in the middle attack to attack users such as phishing

### ISSUE THREAD

**Issue by eexp** [eddy8/lightCMS#31]
The system does not verify the host value. If the host value is modified, the link returned by the website will splice the malicious host value。like this：
![image](https://user-images.githubusercontent.com/53106015/221804877-a7fc0c13-f87d-48fe-8209-4508da1d821e.png)

And  the  header Referer does not verify the value too.  we can jump any website and xss
![image](https://user-images.githubusercontent.com/53106015/221806559-5ec4c9b6-37cc-460f-92eb-4a1b81a13326.png)

**Comment by eddy8** [comment]
https://portswigger.net/web-security/host-header
