### ISSUE TITLE
根据安装步骤进行部署，无法访问。附解决方案

### ISSUE THREAD

**Issue by wasdujk** [eddy8/lightCMS#6]
提示内容：服务器内部错误，请联系管理员
log：
production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at D:\\Project\\cms\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:42)
[stacktrace]

解决方案：
重新生成.env并执行
`php artisan key:generate`

**Comment by eddy8** [comment]
文档中是需要配置环境变量加载.env.pro配置文件的，.env.pro中key是生成好了的，不会有这个问题。可能你没配置好环境变量，默认加载了.env配置文件。

**Comment by eddy8** [comment]
很多人可能不太了解 Laravel 的这个环境配置加载，我修改下文档直接用 .env 默认配置吧
